name: f_weather
description: "An example of the weather app on Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  collection: 1.18.0
  # For making HTTP requests
  http: 1.5.0
  # State management and Depency injection
  flutter_riverpod: 2.6.1
  # Date format and localization
  intl: 0.20.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Generate app logo
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.otf
          weight: 600   
        - asset: assets/fonts/Inter/Inter-Bold.otf
          weight: 700  
        - asset: assets/fonts/Inter/Inter-Italic.otf
          style: italic     

flutter_launcher_icons:
  android: "launcher_icon"
  ios: 
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icon/icon.png" 